CREATE TABLE SPRINTS(
	SPRINT_ID BIGINT AUTO_INCREMENT NOT NULL,
	NAME VARCHAR(20) NOT NULL,
	START_DATE DATE,
	END_DATE DATE,
	DESCRIPTION VARCHAR(50),
	STATUS ENUM('Pending', 'In progress', 'Finished', 'Canceled'),
	PRIMARY KEY(SPRINT_ID)
);

CREATE TABLE USERSTORIES(
	USERSTORY_ID BIGINT AUTO_INCREMENT NOT NULL,
	DESCRIPTION VARCHAR(50),
	COUNT_STORY_POINTS INT,
	STATUS ENUM('To do', 'In progress', 'Review', 'Done'),
	PRIMARY KEY(USERSTORY_ID)
);

CREATE TABLE FILES(
	FILE_ID BIGINT AUTO_INCREMENT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY(FILE_ID)
);

CREATE TABLE SPRINT_FILE(
	FILE_ID BIGINT NOT NULL,
	SPRINT_ID BIGINT NOT NULL,
	FOREIGN KEY(FILE_ID) REFERENCES FILES(FILE_ID),
	FOREIGN KEY(SPRINT_ID) REFERENCES SPRINTS(SPRINT_ID),
	PRIMARY KEY(FILE_ID, SPRINT_ID)
);

CREATE TABLE SPRINT_USERSTORY(
	USERSTORY_ID BIGINT NOT NULL,
	SPRINT_ID BIGINT NOT NULL,
	FOREIGN KEY(USERSTORY_ID) REFERENCES USERSTORIES(USERSTORY_ID),
	FOREIGN KEY(SPRINT_ID) REFERENCES SPRINTS(SPRINT_ID),
	PRIMARY KEY(USERSTORY_ID, SPRINT_ID)
);

